server:
  forward-headers-strategy: native
  shutdown: graceful
  servlet:
    session:
      timeout: 8h
      cookie:
        http-only: true
        same-site: lax
spring:
  datasource:
    password: ${DB_PASSWORD}
  lifecycle:
    timeout-per-shutdown-phase: 30s
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
